default: &default
  adapter: mysql2
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: shorten_url
  username: root
  password: root
  host: localhost

test:
  <<: *default
  database: shorten_url_test
  username: root
  password: root
  host: localhost
